export const API_ROUTES = {
  AUTH: {
    LOGIN: '/api/auth/login',
    SIGNUP: '/api/auth/signup',
    REFRESH: '/api/auth/refresh-token',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    LOGOUT: '/api/auth/logout',
  },
  PROJECT: {
    GET_ALL: '/api/projects',
    GET_BY_ID: (id: string) => `/api/projects/${id}`,
    GET_TEAM_LEADERS: '/api/projects/team-leaders',
    GET_TASKS: (id: string) => `/api/projects/${id}/tasks`,
    CREATE: '/api/projects',
    UPDATE: (id: string) => `/api/projects/${id}`,
    DELETE: (id: string) => `/api/projects/${id}`,
  },
  EMPLOYEE: {
    GET_ALL: '/api/users',
    GET_BY_ID: (id: number) => `/api/users/${id}`,
    GET_ROLES: '/api/users/roles',
    CREATE: '/api/users',
    UPDATE: (id: number) => `/api/users/${id}`,
    DELETE: (id: number) => `/api/users/${id}`,
  },
  TASK: {
    GET_ALL: '/api/tasks',
    GET_BY_ID: (id: number) => `/api/tasks/${id}`,
    GET_MY_PROJECTS: '/api/tasks/my-projects',
    GET_TEAM_MEMBERS: '/api/tasks/team-members',
    CREATE: '/api/tasks',
    UPDATE: (id: number) => `/api/tasks/${id}`,
    DELETE: (id: number) => `/api/tasks/${id}`,
    GET_TEAM_LEAD_DASHBOARD: '/api/tasks/team-lead-dashboard',
  },
  MY_TASKS: {
    GET_DASHBOARD: '/api/my-tasks/dashboard',
    GET_MY_PROJECTS: '/api/my-tasks/my-projects',
    GET_MY_TASKS: '/api/my-tasks/my-tasks',
    UPDATE_STATUS: (id: number) => `/api/my-tasks/${id}/status`,
    GET_COMMENTS: (id: number) => `/api/my-tasks/${id}/comments`,
    ADD_COMMENT: (id: number) => `/api/my-tasks/${id}/comments`,
    UPDATE_COMMENT: (commentId: number) => `/api/my-tasks/${commentId}/comments`,
    DELETE_COMMENT: (commentId: number) => `/api/my-tasks/${commentId}/comments`,
    GET_ATTACHMENTS: (id: number) => `/api/my-tasks/${id}/attachments`,
    ADD_ATTACHMENTS: (id: number) => `/api/my-tasks/${id}/attachments`,
    DELETE_ATTACHMENT: (attachmentId: number) => `/api/my-tasks/${attachmentId}/attachments`,
    DOWNLOAD_ATTACHMENT: (attachmentId: number) => `/api/my-tasks/attachments/${attachmentId}/download`,
  },
  PROFILE: {
    GET: '/api/profile',
    UPDATE: '/api/profile',
    CHANGE_PASSWORD: '/api/profile/change-password',
  },
  ADMIN: {
    GET_DASHBOARD: '/api/admin/dashboard',
  },
  REPORT: {
    GET_EMPLOYEE_PERFORMANCE_REPORT: '/api/admin/reports/employee-performance',
    GET_EMPLOYEE_SUMMARY: '/api/admin/reports/employee-summary',
    GET_TASK_COMPLETION_OVERVIEW: '/api/admin/reports/task-completion-overview',
    GET_TASK_COMPLETION_SUMMARY: '/api/admin/reports/task-completion-summary',
    GET_PROJECT_PROGRESS_OVERVIEW: '/api/admin/reports/project-progress-overview',
    GET_PROJECT_PROGRESS_SUMMARY: '/api/admin/reports/project-progress-summary',
  },
  ATTENDANCE: {
    GET_MONTHLY: '/api/attendance/monthly',
    GET_PENDING_ATTENDANCE: '/api/attendance/pending-review',
    ADD: '/api/attendance',
    ADD_ATTENDANCE_ADMIN: '/api/attendance/admin-fill',
    EDIT: (id: number) => `/api/attendance/${id}`,
    REVIEW_ATTENDANCE: (id: number) => `/api/attendance/${id}/review`,
    APPROVE_ALL_PENDING: '/api/attendance/approve-all-pending',
  },
  LEAVE: {
    GET_MY_LEAVES: '/api/leave/my-leaves',
    GET_PENDING_REVIEW: '/api/leave/pending-review',
    GET_BY_ID: (id: number) => `/api/leave/${id}`,
    APPLY: '/api/leave',
    EDIT: (id: number) => `/api/leave/${id}`,
    REVIEW: (id: number) => `/api/leave/${id}/review`,
    DELETE: (id: number) => `/api/leave/${id}`,
  },
  PUBLIC_HOLIDAY: {
    GET_ALL: '/api/public-holidays',
    GET_BY_ID: (id: number) => `/api/public-holidays/${id}`,
    CREATE: '/api/public-holidays',
    UPDATE: (id: number) => `/api/public-holidays/${id}`,
    DELETE: (id: number) => `/api/public-holidays/${id}`,
  },
};